version: "3"

services:
  external:
    container_name: cnotes-container
    image: cnotes
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod
    restart: unless-stopped
    ports:
      - 3000:3000